### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by ulfryk** [GregRos/parjs#1]
Hi - great library!

…but is there any place with complete docs ?

**Comment by GregRos** [comment]
Thank you! I'm glad you're interested in it.

Unfortunately, there isn't. It's still in active, albeit slow development, and I haven't generated full API docs for it yet. However, the source code is well-documented with jsdoc so if you're using TypeScript you should have a lot of info in your IDE.

I believe I'll get on it within a few months. However, if you feel like helping out, you can generate it from the existing sources (that have full JSDocs) and submit a pull request.

**Comment by GregRos** [comment]
I added full API documentation :smile: https://gregros.github.io/parjs/
