### ISSUE TITLE
readme example fails on 0.6.0 on node

### ISSUE THREAD

**Issue by paultopia** [GregRos/parjs#10]
Just as an initial exploration of the lib, I tried to fire up the example at the start of the readme, and it threw, in relevant part: 

```
TypeError: Cannot read property 'q' of undefined
    at ParjsParser.between ([PATH-TO-MY-REPO]/node_modules/parjs/dist/internal/instance.js:31:28)
```

on node 8.4.0, parjs 0.6.0 installed via npm, and literally just running the code from the first example in the readme, i.e.: 

```
var Parjs = require('parjs').Parjs;
let tupleElement = Parjs.float();
let paddedElement = tupleElement.between(Parjs.spaces);
let separated = paddedElement.manySepBy(Parjs.string(","));
let surrounded = separated.between(Parjs.string("("), Parjs.string(")"));
console.log(surrounded.parse("(1,  2 , 3 )"));

```

In particular, it seems to be throwing on line 31 of internal/instance.js at 
`bet = preceding.q.then(this).then(preceding.q);`

**Comment by paultopia** [comment]
Is there actually a `Parjs.spaces`?  After poking through the code, the nonexistence of that parser would be a good explanation for this error, and I don't see it anywhere in the "Kinds of Parsers" section of [the api docs](https://gregros.github.io/parjs/index.html)... but I can't actually find a complete list of built-in parsers anywhere, so...

**Comment by paultopia** [comment]
aaaaaah.  Should the example be [whitespaces](https://github.com/GregRos/parjs/blob/780fffe22e4968c5003d2a0acdd2fc2b0eb56c31/src/internal/static.ts#L159) rather than spaces?

**Comment by paultopia** [comment]
yep, works with :s/spaces/whitespaces.  Ima just do a documentation pr or something :-)

**Comment by GregRos** [comment]
Thank you! :smile:
