### ISSUE TITLE
StringLen parser uses substring incorrectly, leading to incorrect results

### ISSUE THREAD

**Issue by arbair** [GregRos/parjs#107]
The StringLen parser uses `substring` incorrectly, leading to incorrect results.

```
stringLen(1).pipe(many()).parse("asdf").value

// Expected: ["a", "s", "d", "f"]
// Actual: ["a", "", "s", "sd"]
```

It appears that a previous call to the deprecated `substr` in the `StringLen` parser was replaced with a call to `substring` without updating the second parameter:

https://github.com/GregRos/parjs/blame/f164703821d79956bc1f6cdb250af87e1ff1acb6/src/lib/internal/parsers/string-len.ts#L22

This line should be changed to either:
```
ps.value = input.substring(position, ps.position);
```
or
```
ps.value = input.substring(position, position + length);
```

**Comment by sp3ctum** [comment]
Thanks for the bug report! I appreciate the deep analysis 👍🏻
