### ISSUE TITLE
Try next parser until it succeeds?

### ISSUE THREAD

**Issue by eberfreitas** [GregRos/parjs#126]
Hello friends!

I'm new to parsing and this library so forgive me if this is common knowledge, but I couldn't find the solution...

Is it possible to create a parser combinator that, uppon failing one parser, tries the next one until it succeeds or fail completely?

Thanks!

**Comment by mikavilpas** [comment]
Hi, welcome on board 🙂 

Yes, this is possible using the different ways of dealing with failure here https://github.com/GregRos/parjs?tab=readme-ov-file#dealing-with-failure

Depending on what kind of failure is emitted from your combinators, you need to pick the right way to handle the error. Maybe using `.debug()` can help you (https://github.com/GregRos/parjs/?tab=readme-ov-file#debugging). If you have a minimal example, I can also help figure out what could be done. 👍🏻

**Comment by eberfreitas** [comment]
Hey @mikavilpas! Thank you ❤️ 

I think I finally understand how it should work and I'm unblocked.

Will close this for now. Thank you so much!
