### ISSUE TITLE
.maybe() should allow falsy alternative values.

### ISSUE THREAD

**Issue by tsangal** [GregRos/parjs#14]
Currently using a falsy alternative value (e.g. 0, null, or empty string) in a .maybe() call throws an exception ("Uncaught Error: the inner parser must be quiet if an alternative value is not supplied.") I would argue that .maybe(0), .maybe(null) or .maybe("") should be allowable alternate values.

**Comment by GregRos** [comment]
Yes they are! Thank you for spotting the bug. I will count the number of arguments the function is called with instead of doing the `if(arg)` check which is probably happening.

**Comment by tsangal** [comment]
Thank you for the fix, much appreciated.
