### ISSUE TITLE
Parjs.whitespaces doesn't parse tab characters

### ISSUE THREAD

**Issue by hreinhardt** [GregRos/parjs#18]
Hi,

Running

```
Parjs.whitespaces.parse("\t")
```

will fail, even though the docs state that it should parse tabs. I think the root cause is this: https://github.com/GregRos/parjs/blob/c92628b1ec0c0aefceae30491726580bce5fa5a1/src/lib/internal/implementation/functions/char-indicators.ts#L20

For some inexplicable reason, tab is defined as 0x08 instead of 0x09.

**Comment by GregRos** [comment]
Thank you! I just fixed this, in bb2827944b77009513042f27c743fb6c2f3d59a2.
