### ISSUE TITLE
Is there like a chain combinator?

### ISSUE THREAD

**Issue by waddlaw** [GregRos/parjs#21]
I want to use a combinator like `chain`, but does this library have such a function?
https://github.com/jneen/parsimmon/blob/master/API.md#parserchainnewparserfunc

If there is another way, please let me know.

**Comment by GregRos** [comment]
Hey! Sorry for the late reply. I recently updated the library. I did add a combinator like that - `thenPick`. Hope it's as you wanted it.

**Comment by waddlaw** [comment]
Thanks!!! I'll try using it.
