### ISSUE TITLE
0.12.3 version was published without packaging

### ISSUE THREAD

**Issue by Xanewok** [GregRos/parjs#24]
Related: #22 

As per https://github.com/GregRos/parjs/issues/22#issuecomment-559573923, it seems that 0.12.3 was incorrectly published and can't be used; downgrading to 0.12.2 fixes this issue.

Sorry for the issue duplication but I wanted to shed more light on the issue and bring this to your attention. Could you possibly pack and push a new 0.12.4 version? We'd be very grateful :bowing_man: 

In the meantime, thank you for your hard work and for the awesome package! :star2:

**Comment by GregRos** [comment]
Thank you so much!

I'm sorry I missed all these issues, I had some life stuff going on.

I reran the publish script, and the package works now. I checked it manually to make sure.

**Comment by Xanewok** [comment]
That’s great, thank you so much!
