### ISSUE TITLE
[math example] Expected precedence not matching

### ISSUE THREAD

**Issue by mrcosta** [GregRos/parjs#27]
Hi, I'm trying to use the math parser in a project and I noticed that some examples don't work as expected (or am I'm using incorrectly maybe). I'm trying to fix the issue myself but I could use some help.

### minimum example:

initial expression: `1 + (2) / 2`
expected expression: `+(/(2, 2), 1)`
current result: `/(+(1, 2), 2)`

This also happens with the one written in the documentation: `( 1 + 2 ) * 2 * 2+( 3 * 5   ) / 2 / 2 + 0.25`

Let me know if is something wrong on my side or if I can help in somehow (and thanks a lot for the library)

**Comment by GregRos** [comment]
Thank you! I think one of the changes I made in the library broke the example and I hadn't noticed. 

I don't like how it's written so I just removed it for now. I'll write another math example in the future.
