### ISSUE TITLE
An good way to a parser within a ParjsAction

### ISSUE THREAD

**Issue by digitalheir** [GregRos/parjs#3]
Suppose I want to parse comments in a language and I want to return as the value of the comment without the intial `%`. 

I thought I might wrap a complex parser in a ParjsAction, and only mess around with the return value. But I find it difficult to write such a class:

```
function isOk<T>(res: Reply<T>): res is SuccessReply<T> {
    return res.kind === "OK";
}

class CommentParseAction extends ParjsAction {
    isLoud = true;
    expecting = `a comment line`;

    protected _apply(ps: ParsingState) {
        const res = Parjs.regexp(/^%[^\n]*/);
    
        if (isOk(res)) {
            ps.position = ps.input.length;
            ps.value = res.value;
        } else {
            ps.position = res.trace.position;
            ps.value = "";
        }
        ps.kind = res.kind;
}
```

Of course, in this simple case I could increment the position myself and do not need to wrap parsers. But for complex patterns that would be more difficult. Is there a canonical way to solve this?

**Comment by GregRos** [comment]
That's what quiet parsers are for. Here is an example:
```
let pComment = Parjs.string("%").q.then(Parjs.anyChar.manyTill(Parjs.newline)).str;
```
If you quieten a parser, its result is ignored. You could also use `.map` and ignore the first character, but that's the less natural way.

**Comment by digitalheir** [comment]
Perfect!
