### ISSUE TITLE
Float parser: allow implicit exponentiation sign

### ISSUE THREAD

**Issue by soul-codes** [GregRos/parjs#34]
Currently, something like `1e7` would fail the float parser where it could be interpreted as `1e+7`. FWIW, JavaScript allows `1e7` so it would be nice to have this baked into the standard parser.

**Comment by GregRos** [comment]
Done! Thank you!
https://github.com/GregRos/parjs/commit/70b57be1a5b37db76d87606ce45d427f25fb781e
