### ISSUE TITLE
Publishing new versions is broken on the master branch

### ISSUE THREAD

**Issue by barona-mika-vilpas** [GregRos/parjs#69]
I think I have resolved most build related errors. However, publishing seems broken and in a somewhat unexpected state:

- as far as I can see, the `yarn do-publish` script was added in https://github.com/sp3ctum/parjs/commit/8748b3b08efe60d85b4354472d694827563424a5
- it used `src/publish.ts` to do some source map related magic, but that script was removed in 657f9b3ad68810d792363d4a02e2bed9c2169235

**Comment by GregRos** [comment]
Thankfully it's fixed now :)
