### ISSUE TITLE
Reconsider “quiet” parsers

### ISSUE THREAD

**Issue by barona-mika-vilpas** [GregRos/parjs#73]
> Ages ago I had an interesting system where you could tell a parser to discard its output, which changed its compile-time type to QuietParser. These were called quiet parsers.
> 
> This means that combinators remain very flexible without forcing the user to deal with arrays of multiple outputs when they don’t want to.
> 
> For instance, one use case was to communicate to a combinator such as manySepBy whether you want to the separator’s result to be included in the output. If you did, you’d use a regular (loud) parser, while if you didn’t you’d give it a quiet one. This was an issue in https://github.com/GregRos/parjs/issues/35.
> 
> This means that the result yielded by manySepBy(parser1, parser2) depended on the types of parser1 and parser2. It could be LoudParser<[Output1, Output2]> if neither was quiet, but it could also be Parser<Output1> or Parser<Output2>, as well as QuietParser if all inputs were quiet.
> 
> This kind of thing requires pretty powerful type system features to implement, or else code generation. I managed to make it work when the combinators were instance methods, but when I moved to using the .pipe interface it didn’t seem possible anymore.

This came up in https://github.com/GregRos/parjs/pull/64#issuecomment-1810698810

**Comment by GregRos** [comment]
I've reconsidered them, and decided they cause too many problems.
